### ISSUE TITLE
Element.insertAdjacentHTML is not a function

### ISSUE THREAD

**Issue by leifoolsen** [dmatteo/jsdomify#97]
Element.insertAdjacentHTML works as expected with jsdom, but when I use jsdomify I get the following error: "insertAdjacentHTML is not a function"

**Testcase jsdom:**

``` javascript
import jsdom from 'jsdom'

const doc = jsdom.jsdom('<!doctype html><html><body><div id="mount"></div></body></html>')
const win = doc.defaultView
global.document = doc
global.window = win

const mount = document.querySelector('#mount')
mount.insertAdjacentHTML('beforeend', '<p>FOO</p>')
console.log(mount.innerHTML); // -> <p>FOO</p>
```

**Testcase jsdomify:**

``` javascript
import jsdomify from 'jsdomify'

jsdomify.create('<!doctype html><html><body><div id="mount"></div></body></html>')

const mount = document.querySelector('#mount')
mount.insertAdjacentHTML('beforeend', '<p>FOO</p>'); // -> ERROR!
console.log(mount.innerHTML)
```

**Stacktrace:**

```
TypeError: mount.insertAdjacentHTML is not a function
    at Object.<anonymous> (.istanbul-mocha.config.js:13:7)
    at Module._compile (module.js:398:26)
    at loader (/home/m95265/dev/my/mdl-webpack/node_modules/babel-register/lib/node.js:128:5)
    at Object.require.extensions.(anonymous function) [as .js] (/home/m95265/dev/my/mdl-webpack/node_modules/babel-register/lib/node.js:138:7)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at /home/m95265/dev/my/mdl-webpack/node_modules/mocha/bin/_mocha:310:3
    at Array.forEach (native)
    at Object.<anonymous> (/home/m95265/dev/my/mdl-webpack/node_modules/mocha/bin/_mocha:309:10)
    at Module._compile (module.js:398:26)
    at Object.Module._extensions..js (module.js:405:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:430:10)
    at startup (node.js:141:18)
    at node.js:980:3
```

I do not know if this is a bug in jsdomify or whether I'm using jsdomify with a wrong setup.

Regards
Leif Olsen

**Comment by dmatteo** [comment]
Hi Leif,
the way you're using jsdomify seems ok to me.

I will have to take a look into the issue to see what's going on

**Comment by leifoolsen** [comment]
Hi dmatteo,
Thank you for looking into this.
I can get around the problem temporarily by using Element.innerHTML, but it complicates my tests to some extent.

**Comment by leifoolsen** [comment]
insertAdjacentHTML works in version 2.01. Thanks :thumbsup:

**Comment by dmatteo** [comment]
Great to hear!
